eureka:
  instance:
     preferIpAddress: false   
  client:
    serviceUrl:
       defaultZone: http://netflix-eureka-dymaczew.mybluemix.net/eureka/

# Server configuration
server:
  context-path: /micro
  port: 80

# Spring properties
spring:
  application:
     name: inventory-microservice

  # MySQL Data source configuration
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://169.46.17.190/inventorydb
    username: dbuser
<<<<<<< HEAD
    password: passw0rd
=======
    password: Pass4dbUs3R
>>>>>>> 5a9e966c86901f13bdb53693a64cee3e01754cd4
    port: 3306
    max-active: 4
    testOnBorrow: true
    validationQuery: SELECT 1

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
